apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: canary-91c3787
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: canary
        app: canary
    spec:
      containers:
      - name: canary
        image: ibuchh/ecs-deep-dive:91c3787
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      
